#ifndef COLOR_ENHANCEMENT_GLOBAL_H
#define COLOR_ENHANCEMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COLOR_ENHANCEMENT_LIBRARY)
#  define COLOR_ENHANCEMENT_EXPORT Q_DECL_EXPORT
#else
#  define COLOR_ENHANCEMENT_EXPORT Q_DECL_IMPORT
#endif

#endif // COLOR_ENHANCEMENT_GLOBAL_H
