#ifndef FILTERING_LIB_CUDA_GLOBAL_H
#define FILTERING_LIB_CUDA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILTERING_LIB_CUDA_LIBRARY)
#define FILTERING_LIB_CUDA_EXPORT Q_DECL_EXPORT
#else
#define FILTERING_LIB_CUDA_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERING_LIB_CUDA_GLOBAL_H
